export const APP_NAME = "YouChatt";
const MESSAGE_DB_NAME = "DB.Messages";
const THREAD_DB_NAME = "DB.Threads";
const MESSAGE_USER_REL_DB_NAME = "DB.MessagesUserRead";
const USER_DB_NAME = "DB.Users";
const PROFILE_DB_NAME = "DB.Profiles";
const THREAD_USER_REL_DB_NAME = "DB.ThreadUser";
const THREAD_USER_REL_DEL_DB_NAME = "DB.ThreadDelUser";
const MESSAGE_THREAD_REL_DB_NAME = "DB.MessageThread";


export const DB_CONFIG = {
	MESSAGE_DB_NAME,
	PROFILE_DB_NAME,
	THREAD_DB_NAME,
	MESSAGE_USER_REL_DB_NAME,
	USER_DB_NAME,
	THREAD_USER_REL_DB_NAME,
	THREAD_USER_REL_DEL_DB_NAME,
	MESSAGE_THREAD_REL_DB_NAME,
};
